package Interfaz;

import dominio.*;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class ReanudarPartida extends javax.swing.JFrame {

    private Sistema sistema;
    private VentanaMenu vm;

    public VentanaMenu getVm() {
        return vm;
    }

    public void setVm(VentanaMenu vm) {
        this.vm = vm;
    }
    

    public Sistema getSistema() {
        return sistema;
    }

    public void setSistema(Sistema sistema,VentanaMenu vm) {
        this.sistema = sistema;
        this.vm = vm;
    }

    public ReanudarPartida(Sistema sistema,VentanaMenu vm) {
        this.sistema = sistema;
        this.vm = vm;
        initComponents();
        this.setResizable(false);
         this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono7.png")).getImage());
        this.setLocationRelativeTo(vm);
        this.setDefaultCloseOperation(0);
        this.setTitle("Reanudar Partida");
        this.setSize(620,520);
        this.partidasGuardadas.setListData(this.getSistema().getPartidasGuardadas().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        partidasGuardadas = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        reanudar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        partidasGuardadas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        partidasGuardadas.setModel(new javax.swing.AbstractListModel() {
            final String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(partidasGuardadas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 280, 171);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione la partida");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 40, 170, 30);

        reanudar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        reanudar.setText("Reanudar");
        reanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reanudarActionPerformed(evt);
            }
        });
        jPanel1.add(reanudar);
        reanudar.setBounds(100, 280, 110, 30);

        volver.setBackground(new java.awt.Color(4, 4, 20));
        volver.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-atras (1).png"))); // NOI18N
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver);
        volver.setBounds(410, 360, 70, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/saveroomRE.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 620, 520);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reanudarActionPerformed
if(this.partidasGuardadas.getSelectedValue() == null){
    JOptionPane.showMessageDialog(this,"Debe elegir una partida","Elija una partida",0);
    
}else{
    PartidaGuardada pg = ((PartidaGuardada) this.partidasGuardadas.getSelectedValue());
        Juego reanudada = new Juego();
        Mensajes m = new Mensajes();
        reanudada.setJugador1(pg.getJugador1());
        reanudada.setJugador2(pg.getJugador2());
        reanudada.setJugadorActual(pg.getJugadorActual());
        reanudada.setTablero(pg.getT());
        reanudada.setMensajes(m);
        reanudada.getJugador1().setCubos(pg.getJugador1().getCubos());
        reanudada.getJugador2().setCubos(pg.getJugador2().getCubos());
        
        
        
        
        VentanaTablero vt = new VentanaTablero(pg.isTiempo(),this.getSistema(), reanudada, pg.getCancion(),this.getVm());
        this.actualizarTablero(vt.getBotones(), reanudada.getTablero(), vt);
        vt.setVisible(true);
        this.dispose();
    
}
        
    }//GEN-LAST:event_reanudarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.getVm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed
    public void actualizarTablero(JButton[][] botones, Tablero t, VentanaTablero vt) {
       String red = "\u001B[31mR\u001B[0m";
        String blue = "\033[34mA\u001B[0m";
        String Dosrojo = "\u001B[31m2\u001B[0m";
        String Dosazul = "\033[34m2\u001B[0m";
        String TresRojo = "\u001B[31m3\u001B[0m";
        String TresAzul = "\033[34m3\u001B[0m";
        String CuatroRojo = "\u001B[31m4\u001B[0m";
        String CuatroAzul = "\033[34m4\u001B[0m";
        String CincoRojo = "\u001B[31m5\u001B[0m";
        String CincoAzul = "\033[34m5\u001B[0m";
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[0].length; j++) {
                if (t.getTablero()[i][j].equals(red)) {
                    vt.getBotones()[i][j].setBackground(new Color(255,204,204));
                    vt.getBotones()[i][j].setText("R");

                }
                if (t.getTablero()[i][j].equals(blue)) {
                    vt.getBotones()[i][j].setBackground(new Color(204,204,255));
                    vt.getBotones()[i][j].setText("B");

                }
                if (t.getTablero()[i][j].equals(Dosrojo)) {
                    vt.getBotones()[i][j].setBackground(new Color(255,102,102));
                    vt.getBotones()[i][j].setText("2");
                }
                if (t.getTablero()[i][j].equals(Dosazul)) {
                    vt.getBotones()[i][j].setBackground(new Color(153,153,255));
                    vt.getBotones()[i][j].setText("2");

                }
                if (t.getTablero()[i][j].equals(TresRojo)) {
                    vt.getBotones()[i][j].setBackground(new Color(255,102,102));
                    vt.getBotones()[i][j].setText("3");
                }
                if (t.getTablero()[i][j].equals(TresAzul)) {
                    vt.getBotones()[i][j].setBackground(new Color(102,102,255));
                    vt.getBotones()[i][j].setText("3");
                }
                if (t.getTablero()[i][j].equals(CuatroRojo)) {
                    vt.getBotones()[i][j].setText("4");
                    vt.getBotones()[i][j].setBackground(new Color (204,0,0));
                }
                if (t.getTablero()[i][j].equals(CuatroAzul)) {
                    vt.getBotones()[i][j].setText("4");
                    vt.getBotones()[i][j].setBackground(new Color(0,0,255));
                }
                if (t.getTablero()[i][j].equals(CincoRojo)) {
                    vt.getBotones()[i][j].setBackground(new Color (153,0,0));
                    vt.getBotones()[i][j].setText("5");
                }
                if (t.getTablero()[i][j].equals(CincoAzul)) {
                    vt.getBotones()[i][j].setBackground(new Color(0,0,102));
                    vt.getBotones()[i][j].setText("5");

                }

            }

        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList partidasGuardadas;
    private javax.swing.JButton reanudar;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
